name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key PMAK-65045062d126de00314c2393-529efc03e532ab25155ffeadd0d29e3080
      - name: Run API tests
        run: |
          postman collection run "${{ github.workspace }}/postman/collections/User API.json" --integration-id "148402-${{ github.run_id }}"
          # Lint your API using Postman CLI
          postman api lint e26a6617-30c3-4c79-a5da-055726c0ae09 --integration-id 148402